project:
  type: book
  output-dir: docs

execute:
  echo: true
  warning: false
  message: false

book:
  title: "Political, Racial, and Geographical Trends in the School To Prison Pipeline"
  author:
    - Deepthi Rao dgr2116
  repo-url: https://github.com/Deepthi-Rao/school-to-prison-pipeline
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


